import "./globals.css";
import { VT323 } from "next/font/google";

const vt323 = VT323({
  subsets: ["latin"],
  weight: "400", // ✅ ONLY 400 is supported
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vt323.className} h-screen w-full antialiased`}>
        {children}
      </body>
    </html>
  );
}
